// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	sql "database/sql"

	uuid "github.com/google/uuid"
	db "github.com/mwhite7112/woodpantry-recipes/internal/db"
	mock "github.com/stretchr/testify/mock"
)

// MockQuerier is an autogenerated mock type for the Querier type
type MockQuerier struct {
	mock.Mock
}

type MockQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuerier) EXPECT() *MockQuerier_Expecter {
	return &MockQuerier_Expecter{mock: &_m.Mock}
}

// CreateIngestionJob provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateIngestionJob(ctx context.Context, arg db.CreateIngestionJobParams) (db.IngestionJob, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateIngestionJob")
	}

	var r0 db.IngestionJob
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateIngestionJobParams) (db.IngestionJob, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateIngestionJobParams) db.IngestionJob); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.IngestionJob)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateIngestionJobParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_CreateIngestionJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIngestionJob'
type MockQuerier_CreateIngestionJob_Call struct {
	*mock.Call
}

// CreateIngestionJob is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateIngestionJobParams
func (_e *MockQuerier_Expecter) CreateIngestionJob(ctx interface{}, arg interface{}) *MockQuerier_CreateIngestionJob_Call {
	return &MockQuerier_CreateIngestionJob_Call{Call: _e.mock.On("CreateIngestionJob", ctx, arg)}
}

func (_c *MockQuerier_CreateIngestionJob_Call) Run(run func(ctx context.Context, arg db.CreateIngestionJobParams)) *MockQuerier_CreateIngestionJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateIngestionJobParams))
	})
	return _c
}

func (_c *MockQuerier_CreateIngestionJob_Call) Return(_a0 db.IngestionJob, _a1 error) *MockQuerier_CreateIngestionJob_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_CreateIngestionJob_Call) RunAndReturn(run func(context.Context, db.CreateIngestionJobParams) (db.IngestionJob, error)) *MockQuerier_CreateIngestionJob_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRecipe provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateRecipe(ctx context.Context, arg db.CreateRecipeParams) (db.Recipe, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateRecipe")
	}

	var r0 db.Recipe
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateRecipeParams) (db.Recipe, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateRecipeParams) db.Recipe); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Recipe)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateRecipeParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_CreateRecipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRecipe'
type MockQuerier_CreateRecipe_Call struct {
	*mock.Call
}

// CreateRecipe is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateRecipeParams
func (_e *MockQuerier_Expecter) CreateRecipe(ctx interface{}, arg interface{}) *MockQuerier_CreateRecipe_Call {
	return &MockQuerier_CreateRecipe_Call{Call: _e.mock.On("CreateRecipe", ctx, arg)}
}

func (_c *MockQuerier_CreateRecipe_Call) Run(run func(ctx context.Context, arg db.CreateRecipeParams)) *MockQuerier_CreateRecipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateRecipeParams))
	})
	return _c
}

func (_c *MockQuerier_CreateRecipe_Call) Return(_a0 db.Recipe, _a1 error) *MockQuerier_CreateRecipe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_CreateRecipe_Call) RunAndReturn(run func(context.Context, db.CreateRecipeParams) (db.Recipe, error)) *MockQuerier_CreateRecipe_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRecipeIngredient provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateRecipeIngredient(ctx context.Context, arg db.CreateRecipeIngredientParams) (db.RecipeIngredient, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateRecipeIngredient")
	}

	var r0 db.RecipeIngredient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateRecipeIngredientParams) (db.RecipeIngredient, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateRecipeIngredientParams) db.RecipeIngredient); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.RecipeIngredient)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateRecipeIngredientParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_CreateRecipeIngredient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRecipeIngredient'
type MockQuerier_CreateRecipeIngredient_Call struct {
	*mock.Call
}

// CreateRecipeIngredient is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateRecipeIngredientParams
func (_e *MockQuerier_Expecter) CreateRecipeIngredient(ctx interface{}, arg interface{}) *MockQuerier_CreateRecipeIngredient_Call {
	return &MockQuerier_CreateRecipeIngredient_Call{Call: _e.mock.On("CreateRecipeIngredient", ctx, arg)}
}

func (_c *MockQuerier_CreateRecipeIngredient_Call) Run(run func(ctx context.Context, arg db.CreateRecipeIngredientParams)) *MockQuerier_CreateRecipeIngredient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateRecipeIngredientParams))
	})
	return _c
}

func (_c *MockQuerier_CreateRecipeIngredient_Call) Return(_a0 db.RecipeIngredient, _a1 error) *MockQuerier_CreateRecipeIngredient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_CreateRecipeIngredient_Call) RunAndReturn(run func(context.Context, db.CreateRecipeIngredientParams) (db.RecipeIngredient, error)) *MockQuerier_CreateRecipeIngredient_Call {
	_c.Call.Return(run)
	return _c
}

// CreateStep provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateStep(ctx context.Context, arg db.CreateStepParams) (db.RecipeStep, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateStep")
	}

	var r0 db.RecipeStep
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateStepParams) (db.RecipeStep, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateStepParams) db.RecipeStep); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.RecipeStep)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateStepParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_CreateStep_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStep'
type MockQuerier_CreateStep_Call struct {
	*mock.Call
}

// CreateStep is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateStepParams
func (_e *MockQuerier_Expecter) CreateStep(ctx interface{}, arg interface{}) *MockQuerier_CreateStep_Call {
	return &MockQuerier_CreateStep_Call{Call: _e.mock.On("CreateStep", ctx, arg)}
}

func (_c *MockQuerier_CreateStep_Call) Run(run func(ctx context.Context, arg db.CreateStepParams)) *MockQuerier_CreateStep_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateStepParams))
	})
	return _c
}

func (_c *MockQuerier_CreateStep_Call) Return(_a0 db.RecipeStep, _a1 error) *MockQuerier_CreateStep_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_CreateStep_Call) RunAndReturn(run func(context.Context, db.CreateStepParams) (db.RecipeStep, error)) *MockQuerier_CreateStep_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteIngredientsByRecipe provides a mock function with given fields: ctx, recipeID
func (_m *MockQuerier) DeleteIngredientsByRecipe(ctx context.Context, recipeID uuid.UUID) error {
	ret := _m.Called(ctx, recipeID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteIngredientsByRecipe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, recipeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_DeleteIngredientsByRecipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteIngredientsByRecipe'
type MockQuerier_DeleteIngredientsByRecipe_Call struct {
	*mock.Call
}

// DeleteIngredientsByRecipe is a helper method to define mock.On call
//   - ctx context.Context
//   - recipeID uuid.UUID
func (_e *MockQuerier_Expecter) DeleteIngredientsByRecipe(ctx interface{}, recipeID interface{}) *MockQuerier_DeleteIngredientsByRecipe_Call {
	return &MockQuerier_DeleteIngredientsByRecipe_Call{Call: _e.mock.On("DeleteIngredientsByRecipe", ctx, recipeID)}
}

func (_c *MockQuerier_DeleteIngredientsByRecipe_Call) Run(run func(ctx context.Context, recipeID uuid.UUID)) *MockQuerier_DeleteIngredientsByRecipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockQuerier_DeleteIngredientsByRecipe_Call) Return(_a0 error) *MockQuerier_DeleteIngredientsByRecipe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_DeleteIngredientsByRecipe_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockQuerier_DeleteIngredientsByRecipe_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRecipe provides a mock function with given fields: ctx, id
func (_m *MockQuerier) DeleteRecipe(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRecipe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_DeleteRecipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRecipe'
type MockQuerier_DeleteRecipe_Call struct {
	*mock.Call
}

// DeleteRecipe is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockQuerier_Expecter) DeleteRecipe(ctx interface{}, id interface{}) *MockQuerier_DeleteRecipe_Call {
	return &MockQuerier_DeleteRecipe_Call{Call: _e.mock.On("DeleteRecipe", ctx, id)}
}

func (_c *MockQuerier_DeleteRecipe_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockQuerier_DeleteRecipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockQuerier_DeleteRecipe_Call) Return(_a0 error) *MockQuerier_DeleteRecipe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_DeleteRecipe_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockQuerier_DeleteRecipe_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteStepsByRecipe provides a mock function with given fields: ctx, recipeID
func (_m *MockQuerier) DeleteStepsByRecipe(ctx context.Context, recipeID uuid.UUID) error {
	ret := _m.Called(ctx, recipeID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteStepsByRecipe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, recipeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_DeleteStepsByRecipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteStepsByRecipe'
type MockQuerier_DeleteStepsByRecipe_Call struct {
	*mock.Call
}

// DeleteStepsByRecipe is a helper method to define mock.On call
//   - ctx context.Context
//   - recipeID uuid.UUID
func (_e *MockQuerier_Expecter) DeleteStepsByRecipe(ctx interface{}, recipeID interface{}) *MockQuerier_DeleteStepsByRecipe_Call {
	return &MockQuerier_DeleteStepsByRecipe_Call{Call: _e.mock.On("DeleteStepsByRecipe", ctx, recipeID)}
}

func (_c *MockQuerier_DeleteStepsByRecipe_Call) Run(run func(ctx context.Context, recipeID uuid.UUID)) *MockQuerier_DeleteStepsByRecipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockQuerier_DeleteStepsByRecipe_Call) Return(_a0 error) *MockQuerier_DeleteStepsByRecipe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_DeleteStepsByRecipe_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockQuerier_DeleteStepsByRecipe_Call {
	_c.Call.Return(run)
	return _c
}

// GetIngestionJob provides a mock function with given fields: ctx, id
func (_m *MockQuerier) GetIngestionJob(ctx context.Context, id uuid.UUID) (db.IngestionJob, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetIngestionJob")
	}

	var r0 db.IngestionJob
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (db.IngestionJob, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) db.IngestionJob); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.IngestionJob)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_GetIngestionJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIngestionJob'
type MockQuerier_GetIngestionJob_Call struct {
	*mock.Call
}

// GetIngestionJob is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockQuerier_Expecter) GetIngestionJob(ctx interface{}, id interface{}) *MockQuerier_GetIngestionJob_Call {
	return &MockQuerier_GetIngestionJob_Call{Call: _e.mock.On("GetIngestionJob", ctx, id)}
}

func (_c *MockQuerier_GetIngestionJob_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockQuerier_GetIngestionJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockQuerier_GetIngestionJob_Call) Return(_a0 db.IngestionJob, _a1 error) *MockQuerier_GetIngestionJob_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_GetIngestionJob_Call) RunAndReturn(run func(context.Context, uuid.UUID) (db.IngestionJob, error)) *MockQuerier_GetIngestionJob_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecipe provides a mock function with given fields: ctx, id
func (_m *MockQuerier) GetRecipe(ctx context.Context, id uuid.UUID) (db.Recipe, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRecipe")
	}

	var r0 db.Recipe
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (db.Recipe, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) db.Recipe); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.Recipe)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_GetRecipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecipe'
type MockQuerier_GetRecipe_Call struct {
	*mock.Call
}

// GetRecipe is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockQuerier_Expecter) GetRecipe(ctx interface{}, id interface{}) *MockQuerier_GetRecipe_Call {
	return &MockQuerier_GetRecipe_Call{Call: _e.mock.On("GetRecipe", ctx, id)}
}

func (_c *MockQuerier_GetRecipe_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockQuerier_GetRecipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockQuerier_GetRecipe_Call) Return(_a0 db.Recipe, _a1 error) *MockQuerier_GetRecipe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_GetRecipe_Call) RunAndReturn(run func(context.Context, uuid.UUID) (db.Recipe, error)) *MockQuerier_GetRecipe_Call {
	_c.Call.Return(run)
	return _c
}

// ListIngredientsByRecipe provides a mock function with given fields: ctx, recipeID
func (_m *MockQuerier) ListIngredientsByRecipe(ctx context.Context, recipeID uuid.UUID) ([]db.RecipeIngredient, error) {
	ret := _m.Called(ctx, recipeID)

	if len(ret) == 0 {
		panic("no return value specified for ListIngredientsByRecipe")
	}

	var r0 []db.RecipeIngredient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]db.RecipeIngredient, error)); ok {
		return rf(ctx, recipeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []db.RecipeIngredient); ok {
		r0 = rf(ctx, recipeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.RecipeIngredient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, recipeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_ListIngredientsByRecipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListIngredientsByRecipe'
type MockQuerier_ListIngredientsByRecipe_Call struct {
	*mock.Call
}

// ListIngredientsByRecipe is a helper method to define mock.On call
//   - ctx context.Context
//   - recipeID uuid.UUID
func (_e *MockQuerier_Expecter) ListIngredientsByRecipe(ctx interface{}, recipeID interface{}) *MockQuerier_ListIngredientsByRecipe_Call {
	return &MockQuerier_ListIngredientsByRecipe_Call{Call: _e.mock.On("ListIngredientsByRecipe", ctx, recipeID)}
}

func (_c *MockQuerier_ListIngredientsByRecipe_Call) Run(run func(ctx context.Context, recipeID uuid.UUID)) *MockQuerier_ListIngredientsByRecipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockQuerier_ListIngredientsByRecipe_Call) Return(_a0 []db.RecipeIngredient, _a1 error) *MockQuerier_ListIngredientsByRecipe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_ListIngredientsByRecipe_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]db.RecipeIngredient, error)) *MockQuerier_ListIngredientsByRecipe_Call {
	_c.Call.Return(run)
	return _c
}

// ListRecipes provides a mock function with given fields: ctx
func (_m *MockQuerier) ListRecipes(ctx context.Context) ([]db.Recipe, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListRecipes")
	}

	var r0 []db.Recipe
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]db.Recipe, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []db.Recipe); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Recipe)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_ListRecipes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRecipes'
type MockQuerier_ListRecipes_Call struct {
	*mock.Call
}

// ListRecipes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQuerier_Expecter) ListRecipes(ctx interface{}) *MockQuerier_ListRecipes_Call {
	return &MockQuerier_ListRecipes_Call{Call: _e.mock.On("ListRecipes", ctx)}
}

func (_c *MockQuerier_ListRecipes_Call) Run(run func(ctx context.Context)) *MockQuerier_ListRecipes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockQuerier_ListRecipes_Call) Return(_a0 []db.Recipe, _a1 error) *MockQuerier_ListRecipes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_ListRecipes_Call) RunAndReturn(run func(context.Context) ([]db.Recipe, error)) *MockQuerier_ListRecipes_Call {
	_c.Call.Return(run)
	return _c
}

// ListRecipesByCookTime provides a mock function with given fields: ctx, cookMinutes
func (_m *MockQuerier) ListRecipesByCookTime(ctx context.Context, cookMinutes sql.NullInt32) ([]db.Recipe, error) {
	ret := _m.Called(ctx, cookMinutes)

	if len(ret) == 0 {
		panic("no return value specified for ListRecipesByCookTime")
	}

	var r0 []db.Recipe
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sql.NullInt32) ([]db.Recipe, error)); ok {
		return rf(ctx, cookMinutes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sql.NullInt32) []db.Recipe); ok {
		r0 = rf(ctx, cookMinutes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Recipe)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, sql.NullInt32) error); ok {
		r1 = rf(ctx, cookMinutes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_ListRecipesByCookTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRecipesByCookTime'
type MockQuerier_ListRecipesByCookTime_Call struct {
	*mock.Call
}

// ListRecipesByCookTime is a helper method to define mock.On call
//   - ctx context.Context
//   - cookMinutes sql.NullInt32
func (_e *MockQuerier_Expecter) ListRecipesByCookTime(ctx interface{}, cookMinutes interface{}) *MockQuerier_ListRecipesByCookTime_Call {
	return &MockQuerier_ListRecipesByCookTime_Call{Call: _e.mock.On("ListRecipesByCookTime", ctx, cookMinutes)}
}

func (_c *MockQuerier_ListRecipesByCookTime_Call) Run(run func(ctx context.Context, cookMinutes sql.NullInt32)) *MockQuerier_ListRecipesByCookTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sql.NullInt32))
	})
	return _c
}

func (_c *MockQuerier_ListRecipesByCookTime_Call) Return(_a0 []db.Recipe, _a1 error) *MockQuerier_ListRecipesByCookTime_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_ListRecipesByCookTime_Call) RunAndReturn(run func(context.Context, sql.NullInt32) ([]db.Recipe, error)) *MockQuerier_ListRecipesByCookTime_Call {
	_c.Call.Return(run)
	return _c
}

// ListRecipesByTag provides a mock function with given fields: ctx, tags
func (_m *MockQuerier) ListRecipesByTag(ctx context.Context, tags []string) ([]db.Recipe, error) {
	ret := _m.Called(ctx, tags)

	if len(ret) == 0 {
		panic("no return value specified for ListRecipesByTag")
	}

	var r0 []db.Recipe
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]db.Recipe, error)); ok {
		return rf(ctx, tags)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []db.Recipe); ok {
		r0 = rf(ctx, tags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Recipe)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, tags)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_ListRecipesByTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRecipesByTag'
type MockQuerier_ListRecipesByTag_Call struct {
	*mock.Call
}

// ListRecipesByTag is a helper method to define mock.On call
//   - ctx context.Context
//   - tags []string
func (_e *MockQuerier_Expecter) ListRecipesByTag(ctx interface{}, tags interface{}) *MockQuerier_ListRecipesByTag_Call {
	return &MockQuerier_ListRecipesByTag_Call{Call: _e.mock.On("ListRecipesByTag", ctx, tags)}
}

func (_c *MockQuerier_ListRecipesByTag_Call) Run(run func(ctx context.Context, tags []string)) *MockQuerier_ListRecipesByTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockQuerier_ListRecipesByTag_Call) Return(_a0 []db.Recipe, _a1 error) *MockQuerier_ListRecipesByTag_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_ListRecipesByTag_Call) RunAndReturn(run func(context.Context, []string) ([]db.Recipe, error)) *MockQuerier_ListRecipesByTag_Call {
	_c.Call.Return(run)
	return _c
}

// ListRecipesByTitle provides a mock function with given fields: ctx, dollar_1
func (_m *MockQuerier) ListRecipesByTitle(ctx context.Context, dollar_1 sql.NullString) ([]db.Recipe, error) {
	ret := _m.Called(ctx, dollar_1)

	if len(ret) == 0 {
		panic("no return value specified for ListRecipesByTitle")
	}

	var r0 []db.Recipe
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sql.NullString) ([]db.Recipe, error)); ok {
		return rf(ctx, dollar_1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sql.NullString) []db.Recipe); ok {
		r0 = rf(ctx, dollar_1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Recipe)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, sql.NullString) error); ok {
		r1 = rf(ctx, dollar_1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_ListRecipesByTitle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRecipesByTitle'
type MockQuerier_ListRecipesByTitle_Call struct {
	*mock.Call
}

// ListRecipesByTitle is a helper method to define mock.On call
//   - ctx context.Context
//   - dollar_1 sql.NullString
func (_e *MockQuerier_Expecter) ListRecipesByTitle(ctx interface{}, dollar_1 interface{}) *MockQuerier_ListRecipesByTitle_Call {
	return &MockQuerier_ListRecipesByTitle_Call{Call: _e.mock.On("ListRecipesByTitle", ctx, dollar_1)}
}

func (_c *MockQuerier_ListRecipesByTitle_Call) Run(run func(ctx context.Context, dollar_1 sql.NullString)) *MockQuerier_ListRecipesByTitle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sql.NullString))
	})
	return _c
}

func (_c *MockQuerier_ListRecipesByTitle_Call) Return(_a0 []db.Recipe, _a1 error) *MockQuerier_ListRecipesByTitle_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_ListRecipesByTitle_Call) RunAndReturn(run func(context.Context, sql.NullString) ([]db.Recipe, error)) *MockQuerier_ListRecipesByTitle_Call {
	_c.Call.Return(run)
	return _c
}

// ListStepsByRecipe provides a mock function with given fields: ctx, recipeID
func (_m *MockQuerier) ListStepsByRecipe(ctx context.Context, recipeID uuid.UUID) ([]db.RecipeStep, error) {
	ret := _m.Called(ctx, recipeID)

	if len(ret) == 0 {
		panic("no return value specified for ListStepsByRecipe")
	}

	var r0 []db.RecipeStep
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]db.RecipeStep, error)); ok {
		return rf(ctx, recipeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []db.RecipeStep); ok {
		r0 = rf(ctx, recipeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.RecipeStep)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, recipeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_ListStepsByRecipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListStepsByRecipe'
type MockQuerier_ListStepsByRecipe_Call struct {
	*mock.Call
}

// ListStepsByRecipe is a helper method to define mock.On call
//   - ctx context.Context
//   - recipeID uuid.UUID
func (_e *MockQuerier_Expecter) ListStepsByRecipe(ctx interface{}, recipeID interface{}) *MockQuerier_ListStepsByRecipe_Call {
	return &MockQuerier_ListStepsByRecipe_Call{Call: _e.mock.On("ListStepsByRecipe", ctx, recipeID)}
}

func (_c *MockQuerier_ListStepsByRecipe_Call) Run(run func(ctx context.Context, recipeID uuid.UUID)) *MockQuerier_ListStepsByRecipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockQuerier_ListStepsByRecipe_Call) Return(_a0 []db.RecipeStep, _a1 error) *MockQuerier_ListStepsByRecipe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_ListStepsByRecipe_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]db.RecipeStep, error)) *MockQuerier_ListStepsByRecipe_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateIngestionJobStaged provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) UpdateIngestionJobStaged(ctx context.Context, arg db.UpdateIngestionJobStagedParams) (db.IngestionJob, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateIngestionJobStaged")
	}

	var r0 db.IngestionJob
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateIngestionJobStagedParams) (db.IngestionJob, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateIngestionJobStagedParams) db.IngestionJob); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.IngestionJob)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateIngestionJobStagedParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_UpdateIngestionJobStaged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateIngestionJobStaged'
type MockQuerier_UpdateIngestionJobStaged_Call struct {
	*mock.Call
}

// UpdateIngestionJobStaged is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateIngestionJobStagedParams
func (_e *MockQuerier_Expecter) UpdateIngestionJobStaged(ctx interface{}, arg interface{}) *MockQuerier_UpdateIngestionJobStaged_Call {
	return &MockQuerier_UpdateIngestionJobStaged_Call{Call: _e.mock.On("UpdateIngestionJobStaged", ctx, arg)}
}

func (_c *MockQuerier_UpdateIngestionJobStaged_Call) Run(run func(ctx context.Context, arg db.UpdateIngestionJobStagedParams)) *MockQuerier_UpdateIngestionJobStaged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateIngestionJobStagedParams))
	})
	return _c
}

func (_c *MockQuerier_UpdateIngestionJobStaged_Call) Return(_a0 db.IngestionJob, _a1 error) *MockQuerier_UpdateIngestionJobStaged_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_UpdateIngestionJobStaged_Call) RunAndReturn(run func(context.Context, db.UpdateIngestionJobStagedParams) (db.IngestionJob, error)) *MockQuerier_UpdateIngestionJobStaged_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateIngestionJobStatus provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) UpdateIngestionJobStatus(ctx context.Context, arg db.UpdateIngestionJobStatusParams) (db.IngestionJob, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateIngestionJobStatus")
	}

	var r0 db.IngestionJob
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateIngestionJobStatusParams) (db.IngestionJob, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateIngestionJobStatusParams) db.IngestionJob); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.IngestionJob)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateIngestionJobStatusParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_UpdateIngestionJobStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateIngestionJobStatus'
type MockQuerier_UpdateIngestionJobStatus_Call struct {
	*mock.Call
}

// UpdateIngestionJobStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateIngestionJobStatusParams
func (_e *MockQuerier_Expecter) UpdateIngestionJobStatus(ctx interface{}, arg interface{}) *MockQuerier_UpdateIngestionJobStatus_Call {
	return &MockQuerier_UpdateIngestionJobStatus_Call{Call: _e.mock.On("UpdateIngestionJobStatus", ctx, arg)}
}

func (_c *MockQuerier_UpdateIngestionJobStatus_Call) Run(run func(ctx context.Context, arg db.UpdateIngestionJobStatusParams)) *MockQuerier_UpdateIngestionJobStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateIngestionJobStatusParams))
	})
	return _c
}

func (_c *MockQuerier_UpdateIngestionJobStatus_Call) Return(_a0 db.IngestionJob, _a1 error) *MockQuerier_UpdateIngestionJobStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_UpdateIngestionJobStatus_Call) RunAndReturn(run func(context.Context, db.UpdateIngestionJobStatusParams) (db.IngestionJob, error)) *MockQuerier_UpdateIngestionJobStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRecipe provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) UpdateRecipe(ctx context.Context, arg db.UpdateRecipeParams) (db.Recipe, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRecipe")
	}

	var r0 db.Recipe
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateRecipeParams) (db.Recipe, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateRecipeParams) db.Recipe); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Recipe)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateRecipeParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_UpdateRecipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRecipe'
type MockQuerier_UpdateRecipe_Call struct {
	*mock.Call
}

// UpdateRecipe is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateRecipeParams
func (_e *MockQuerier_Expecter) UpdateRecipe(ctx interface{}, arg interface{}) *MockQuerier_UpdateRecipe_Call {
	return &MockQuerier_UpdateRecipe_Call{Call: _e.mock.On("UpdateRecipe", ctx, arg)}
}

func (_c *MockQuerier_UpdateRecipe_Call) Run(run func(ctx context.Context, arg db.UpdateRecipeParams)) *MockQuerier_UpdateRecipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateRecipeParams))
	})
	return _c
}

func (_c *MockQuerier_UpdateRecipe_Call) Return(_a0 db.Recipe, _a1 error) *MockQuerier_UpdateRecipe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_UpdateRecipe_Call) RunAndReturn(run func(context.Context, db.UpdateRecipeParams) (db.Recipe, error)) *MockQuerier_UpdateRecipe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQuerier creates a new instance of MockQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuerier {
	mock := &MockQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
