# Advisory lint config - runs in CI but does NOT block PRs.
# Posts inline annotations so issues are visible, but merge is not gated.
#
# Based on https://github.com/maratori/golangci-lint-config (golden config v2.10.1)
# Trimmed for the woodpantry-recipes project.

version: "2"

issues:
  max-same-issues: 50

formatters:
  enable:
    - goimports
    - golines
  settings:
    goimports:
      local-prefixes:
        - github.com/mwhite7112
    golines:
      max-len: 120

linters:
  enable:
    # --- correctness / safety (also in blocking config) ---
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - copyloopvar
    - depguard
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forbidigo
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocritic
    - gomoddirectives
    - gosec
    - govet
    - ineffassign
    - intrange
    - loggercheck
    - makezero
    - mirror
    - musttag
    - nilerr
    - nilnesserr
    - noctx
    - nolintlint
    - nosprintfhostport
    - predeclared
    - protogetter
    - reassign
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - staticcheck
    - testifylint
    - tparallel
    - unconvert
    - unparam
    - unqueryvet
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign

    # --- quality / style (advisory only) ---
    - cyclop
    - dupl
    - embeddedstructfieldcheck
    - funcorder
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godoclint
    - godot
    - goprintffuncname
    - iface
    - iotamixing
    - mnd
    - modernize
    - nakedret
    - nestif
    - nilnil
    - nonamedreturns
    - perfsprint
    - promlinter
    - recvcheck
    - revive
    - sloglint
    - testableexamples
    # - testpackage # disabled: white-box tests used intentionally
    - whitespace

  settings:
    cyclop:
      max-complexity: 30
      package-average: 10.0

    depguard:
      rules:
        "deprecated":
          files: ["$all"]
          deny:
            - pkg: github.com/golang/protobuf
              desc: Use google.golang.org/protobuf instead
            - pkg: github.com/satori/go.uuid
              desc: Use github.com/google/uuid instead
            - pkg: github.com/gofrs/uuid$
              desc: Use github.com/gofrs/uuid/v5 or later
        "non-test files":
          files: ["!$test"]
          deny:
            - pkg: math/rand$
              desc: Use math/rand/v2 instead
        "non-main files":
          files: ["!**/main.go"]
          deny:
            - pkg: log$
              desc: Use log/slog instead

    embeddedstructfieldcheck:
      forbid-mutex: true

    errcheck:
      check-type-assertions: true

    exhaustive:
      check: [switch, map]

    funcorder:
      struct-method: false

    funlen:
      lines: 100
      statements: 50

    gochecksumtype:
      default-signifies-exhaustive: false

    gocognit:
      min-complexity: 25

    gocritic:
      settings:
        captLocal:
          paramsOnly: false
        underef:
          skipRecvDeref: false

    godoclint:
      enable:
        - no-unused-link
        - require-stdlib-doclink

    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow

    mnd:
      ignored-functions:
        - args.Error
        - flag.Arg
        - flag.Duration.*
        - flag.Float.*
        - flag.Int.*
        - flag.Uint.*
        - os.Chmod
        - os.Mkdir.*
        - os.OpenFile
        - os.WriteFile
        - prometheus.ExponentialBuckets.*
        - prometheus.LinearBuckets

    nakedret:
      max-func-lines: 0

    nolintlint:
      allow-no-explanation: [errcheck, funlen, gocognit, golines]
      require-explanation: true
      require-specific: true

    perfsprint:
      strconcat: false

    reassign:
      patterns: [".*"]

    rowserrcheck:
      packages: [github.com/jmoiron/sqlx]

    sloglint:
      no-global: all
      context: scope

    staticcheck:
      checks: [all, -ST1000, -ST1016, -QF1008]

    usetesting:
      os-temp-dir: true

  exclusions:
    warn-unused: true
    presets:
      - std-error-handling
      - common-false-positives
    rules:
      - source: 'TODO'
        linters: [godot]
      - text: 'should have a package comment'
        linters: [revive]
      - text: 'exported \S+ \S+ should have comment( \(or a comment on this block\))? or be unexported'
        linters: [revive]
      - text: 'package comment should be of the form ".+"'
        source: '// ?(nolint|TODO)'
        linters: [revive]
      - text: 'comment on exported \S+ \S+ should be of the form ".+"'
        source: '// ?(nolint|TODO)'
        linters: [revive, staticcheck]
      - path: '_test\.go'
        linters: [bodyclose, dupl, errcheck, funlen, goconst, gosec, noctx, wrapcheck]
      # gosec false positives
      - linters: [gosec]
        text: 'G104'
        path: 'internal/api/'
      - linters: [gosec]
        text: 'G706'
      - linters: [gosec]
        text: 'G704'
      - linters: [gosec]
        text: 'G114'
      # revive false positives
      - linters: [revive]
        text: "parameter 'r' seems to be unused"
      - linters: [revive]
        text: 'var-naming: avoid meaningless package names'
        path: 'internal/api/'
      # sloglint: global slog unavoidable in startup path
      - linters: [sloglint]
        path: '^cmd/'
      # noctx: sqlDB.Ping at startup has no context available
      - linters: [noctx]
        path: '^cmd/'
