// Code generated by mockery v2.53.5. DO NOT EDIT.

package service

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockLLMExtractor is an autogenerated mock type for the LLMExtractor type
type MockLLMExtractor struct {
	mock.Mock
}

type MockLLMExtractor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLLMExtractor) EXPECT() *MockLLMExtractor_Expecter {
	return &MockLLMExtractor_Expecter{mock: &_m.Mock}
}

// ExtractRecipe provides a mock function with given fields: ctx, rawText
func (_m *MockLLMExtractor) ExtractRecipe(ctx context.Context, rawText string) (*StagedRecipe, error) {
	ret := _m.Called(ctx, rawText)

	if len(ret) == 0 {
		panic("no return value specified for ExtractRecipe")
	}

	var r0 *StagedRecipe
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*StagedRecipe, error)); ok {
		return rf(ctx, rawText)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *StagedRecipe); ok {
		r0 = rf(ctx, rawText)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*StagedRecipe)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, rawText)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLLMExtractor_ExtractRecipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractRecipe'
type MockLLMExtractor_ExtractRecipe_Call struct {
	*mock.Call
}

// ExtractRecipe is a helper method to define mock.On call
//   - ctx context.Context
//   - rawText string
func (_e *MockLLMExtractor_Expecter) ExtractRecipe(ctx interface{}, rawText interface{}) *MockLLMExtractor_ExtractRecipe_Call {
	return &MockLLMExtractor_ExtractRecipe_Call{Call: _e.mock.On("ExtractRecipe", ctx, rawText)}
}

func (_c *MockLLMExtractor_ExtractRecipe_Call) Run(run func(ctx context.Context, rawText string)) *MockLLMExtractor_ExtractRecipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLLMExtractor_ExtractRecipe_Call) Return(_a0 *StagedRecipe, _a1 error) *MockLLMExtractor_ExtractRecipe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLLMExtractor_ExtractRecipe_Call) RunAndReturn(run func(context.Context, string) (*StagedRecipe, error)) *MockLLMExtractor_ExtractRecipe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLLMExtractor creates a new instance of MockLLMExtractor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLLMExtractor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLLMExtractor {
	mock := &MockLLMExtractor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
