// Code generated by mockery v2.53.5. DO NOT EDIT.

package service

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockIngredientResolver is an autogenerated mock type for the IngredientResolver type
type MockIngredientResolver struct {
	mock.Mock
}

type MockIngredientResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIngredientResolver) EXPECT() *MockIngredientResolver_Expecter {
	return &MockIngredientResolver_Expecter{mock: &_m.Mock}
}

// ResolveIngredient provides a mock function with given fields: ctx, name
func (_m *MockIngredientResolver) ResolveIngredient(ctx context.Context, name string) (uuid.UUID, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for ResolveIngredient")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (uuid.UUID, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) uuid.UUID); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIngredientResolver_ResolveIngredient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveIngredient'
type MockIngredientResolver_ResolveIngredient_Call struct {
	*mock.Call
}

// ResolveIngredient is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockIngredientResolver_Expecter) ResolveIngredient(ctx interface{}, name interface{}) *MockIngredientResolver_ResolveIngredient_Call {
	return &MockIngredientResolver_ResolveIngredient_Call{Call: _e.mock.On("ResolveIngredient", ctx, name)}
}

func (_c *MockIngredientResolver_ResolveIngredient_Call) Run(run func(ctx context.Context, name string)) *MockIngredientResolver_ResolveIngredient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIngredientResolver_ResolveIngredient_Call) Return(_a0 uuid.UUID, _a1 error) *MockIngredientResolver_ResolveIngredient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIngredientResolver_ResolveIngredient_Call) RunAndReturn(run func(context.Context, string) (uuid.UUID, error)) *MockIngredientResolver_ResolveIngredient_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIngredientResolver creates a new instance of MockIngredientResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIngredientResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIngredientResolver {
	mock := &MockIngredientResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
