// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ingestion_jobs.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createIngestionJob = `-- name: CreateIngestionJob :one
INSERT INTO ingestion_jobs (type, raw_input)
VALUES ($1, $2)
RETURNING id, type, raw_input, status, staged_data, created_at
`

type CreateIngestionJobParams struct {
	Type     string
	RawInput string
}

func (q *Queries) CreateIngestionJob(ctx context.Context, arg CreateIngestionJobParams) (IngestionJob, error) {
	row := q.db.QueryRowContext(ctx, createIngestionJob, arg.Type, arg.RawInput)
	var i IngestionJob
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.RawInput,
		&i.Status,
		&i.StagedData,
		&i.CreatedAt,
	)
	return i, err
}

const getIngestionJob = `-- name: GetIngestionJob :one
SELECT id, type, raw_input, status, staged_data, created_at
FROM ingestion_jobs WHERE id = $1
`

func (q *Queries) GetIngestionJob(ctx context.Context, id uuid.UUID) (IngestionJob, error) {
	row := q.db.QueryRowContext(ctx, getIngestionJob, id)
	var i IngestionJob
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.RawInput,
		&i.Status,
		&i.StagedData,
		&i.CreatedAt,
	)
	return i, err
}

const updateIngestionJobStaged = `-- name: UpdateIngestionJobStaged :one
UPDATE ingestion_jobs
SET status = 'staged', staged_data = $2
WHERE id = $1
RETURNING id, type, raw_input, status, staged_data, created_at
`

type UpdateIngestionJobStagedParams struct {
	ID         uuid.UUID
	StagedData *json.RawMessage
}

func (q *Queries) UpdateIngestionJobStaged(ctx context.Context, arg UpdateIngestionJobStagedParams) (IngestionJob, error) {
	row := q.db.QueryRowContext(ctx, updateIngestionJobStaged, arg.ID, arg.StagedData)
	var i IngestionJob
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.RawInput,
		&i.Status,
		&i.StagedData,
		&i.CreatedAt,
	)
	return i, err
}

const updateIngestionJobStatus = `-- name: UpdateIngestionJobStatus :one
UPDATE ingestion_jobs
SET status = $2
WHERE id = $1
RETURNING id, type, raw_input, status, staged_data, created_at
`

type UpdateIngestionJobStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateIngestionJobStatus(ctx context.Context, arg UpdateIngestionJobStatusParams) (IngestionJob, error) {
	row := q.db.QueryRowContext(ctx, updateIngestionJobStatus, arg.ID, arg.Status)
	var i IngestionJob
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.RawInput,
		&i.Status,
		&i.StagedData,
		&i.CreatedAt,
	)
	return i, err
}
