// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Recipe struct {
	ID          uuid.UUID
	Title       string
	Description sql.NullString
	SourceURL   sql.NullString
	Servings    sql.NullInt32
	PrepMinutes sql.NullInt32
	CookMinutes sql.NullInt32
	Tags        []string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type RecipeStep struct {
	ID          uuid.UUID
	RecipeID    uuid.UUID
	StepNumber  int32
	Instruction string
}

type RecipeIngredient struct {
	ID               uuid.UUID
	RecipeID         uuid.UUID
	IngredientID     uuid.UUID
	Quantity         sql.NullFloat64
	Unit             sql.NullString
	IsOptional       bool
	PreparationNotes sql.NullString
}

type IngestionJob struct {
	ID         uuid.UUID
	Type       string
	RawInput   string
	Status     string
	StagedData json.RawMessage
	CreatedAt  time.Time
}
