// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CreateIngestionJob(ctx context.Context, arg CreateIngestionJobParams) (IngestionJob, error)
	CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error)
	CreateRecipeIngredient(ctx context.Context, arg CreateRecipeIngredientParams) (RecipeIngredient, error)
	CreateStep(ctx context.Context, arg CreateStepParams) (RecipeStep, error)
	DeleteIngredientsByRecipe(ctx context.Context, recipeID uuid.UUID) error
	DeleteRecipe(ctx context.Context, id uuid.UUID) error
	DeleteStepsByRecipe(ctx context.Context, recipeID uuid.UUID) error
	GetIngestionJob(ctx context.Context, id uuid.UUID) (IngestionJob, error)
	GetRecipe(ctx context.Context, id uuid.UUID) (Recipe, error)
	ListIngredientsByRecipe(ctx context.Context, recipeID uuid.UUID) ([]RecipeIngredient, error)
	ListRecipes(ctx context.Context) ([]Recipe, error)
	ListRecipesByCookTime(ctx context.Context, cookMinutes sql.NullInt32) ([]Recipe, error)
	ListRecipesByTag(ctx context.Context, tags []string) ([]Recipe, error)
	ListRecipesByTitle(ctx context.Context, dollar_1 sql.NullString) ([]Recipe, error)
	ListStepsByRecipe(ctx context.Context, recipeID uuid.UUID) ([]RecipeStep, error)
	UpdateIngestionJobStaged(ctx context.Context, arg UpdateIngestionJobStagedParams) (IngestionJob, error)
	UpdateIngestionJobStatus(ctx context.Context, arg UpdateIngestionJobStatusParams) (IngestionJob, error)
	UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error)
}

var _ Querier = (*Queries)(nil)
