// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recipes.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createRecipe = `-- name: CreateRecipe :one
INSERT INTO recipes (title, description, source_url, servings, prep_minutes, cook_minutes, tags)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, title, description, source_url, servings, prep_minutes, cook_minutes, tags, created_at, updated_at
`

type CreateRecipeParams struct {
	Title       string
	Description sql.NullString
	SourceUrl   sql.NullString
	Servings    sql.NullInt32
	PrepMinutes sql.NullInt32
	CookMinutes sql.NullInt32
	Tags        []string
}

func (q *Queries) CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, createRecipe,
		arg.Title,
		arg.Description,
		arg.SourceUrl,
		arg.Servings,
		arg.PrepMinutes,
		arg.CookMinutes,
		pq.Array(arg.Tags),
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.SourceUrl,
		&i.Servings,
		&i.PrepMinutes,
		&i.CookMinutes,
		pq.Array(&i.Tags),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRecipe = `-- name: DeleteRecipe :exec
DELETE FROM recipes WHERE id = $1
`

func (q *Queries) DeleteRecipe(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRecipe, id)
	return err
}

const getRecipe = `-- name: GetRecipe :one
SELECT id, title, description, source_url, servings, prep_minutes, cook_minutes, tags, created_at, updated_at
FROM recipes WHERE id = $1
`

func (q *Queries) GetRecipe(ctx context.Context, id uuid.UUID) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, getRecipe, id)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.SourceUrl,
		&i.Servings,
		&i.PrepMinutes,
		&i.CookMinutes,
		pq.Array(&i.Tags),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRecipes = `-- name: ListRecipes :many
SELECT id, title, description, source_url, servings, prep_minutes, cook_minutes, tags, created_at, updated_at
FROM recipes
ORDER BY created_at DESC
`

func (q *Queries) ListRecipes(ctx context.Context) ([]Recipe, error) {
	rows, err := q.db.QueryContext(ctx, listRecipes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.SourceUrl,
			&i.Servings,
			&i.PrepMinutes,
			&i.CookMinutes,
			pq.Array(&i.Tags),
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipesByCookTime = `-- name: ListRecipesByCookTime :many
SELECT id, title, description, source_url, servings, prep_minutes, cook_minutes, tags, created_at, updated_at
FROM recipes
WHERE cook_minutes <= $1
ORDER BY created_at DESC
`

func (q *Queries) ListRecipesByCookTime(ctx context.Context, cookMinutes sql.NullInt32) ([]Recipe, error) {
	rows, err := q.db.QueryContext(ctx, listRecipesByCookTime, cookMinutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.SourceUrl,
			&i.Servings,
			&i.PrepMinutes,
			&i.CookMinutes,
			pq.Array(&i.Tags),
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipesByTag = `-- name: ListRecipesByTag :many
SELECT id, title, description, source_url, servings, prep_minutes, cook_minutes, tags, created_at, updated_at
FROM recipes
WHERE $1 = ANY(tags)
ORDER BY created_at DESC
`

func (q *Queries) ListRecipesByTag(ctx context.Context, tags []string) ([]Recipe, error) {
	rows, err := q.db.QueryContext(ctx, listRecipesByTag, pq.Array(tags))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.SourceUrl,
			&i.Servings,
			&i.PrepMinutes,
			&i.CookMinutes,
			pq.Array(&i.Tags),
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipesByTitle = `-- name: ListRecipesByTitle :many
SELECT id, title, description, source_url, servings, prep_minutes, cook_minutes, tags, created_at, updated_at
FROM recipes
WHERE title ILIKE '%' || $1 || '%'
ORDER BY created_at DESC
`

func (q *Queries) ListRecipesByTitle(ctx context.Context, dollar_1 sql.NullString) ([]Recipe, error) {
	rows, err := q.db.QueryContext(ctx, listRecipesByTitle, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.SourceUrl,
			&i.Servings,
			&i.PrepMinutes,
			&i.CookMinutes,
			pq.Array(&i.Tags),
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecipe = `-- name: UpdateRecipe :one
UPDATE recipes
SET title = $2, description = $3, source_url = $4, servings = $5,
    prep_minutes = $6, cook_minutes = $7, tags = $8, updated_at = now()
WHERE id = $1
RETURNING id, title, description, source_url, servings, prep_minutes, cook_minutes, tags, created_at, updated_at
`

type UpdateRecipeParams struct {
	ID          uuid.UUID
	Title       string
	Description sql.NullString
	SourceUrl   sql.NullString
	Servings    sql.NullInt32
	PrepMinutes sql.NullInt32
	CookMinutes sql.NullInt32
	Tags        []string
}

func (q *Queries) UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, updateRecipe,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.SourceUrl,
		arg.Servings,
		arg.PrepMinutes,
		arg.CookMinutes,
		pq.Array(arg.Tags),
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.SourceUrl,
		&i.Servings,
		&i.PrepMinutes,
		&i.CookMinutes,
		pq.Array(&i.Tags),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
